### ISSUE TITLE
Create detail pages

### ISSUE THREAD

**Issue by kochch1337** [kochch1337/Capstone-Project#1]
## Value Proposition

**As a**
User  
**I want to**
to see detail pages to my top level data and navigate between the pages
**so that**
I can better visualize the given data
​

## Description
Detailpages for all areas and items in the tree must be created
<img width="288" alt="Screenshot 2022-11-15 at 11 01 27" src="https://user-images.githubusercontent.com/113910347/201890496-a14f42bd-59a2-4e75-926e-5e7730854041.png">
<img width="288" alt="Screenshot 2022-11-15 at 11 01 14" src="https://user-images.githubusercontent.com/113910347/201890623-df6c40e9-ed20-43e8-ae75-e2aa5b957c95.png">
<img width="288" alt="Screenshot 2022-11-15 at 11 01 06" src="https://user-images.githubusercontent.com/113910347/201890651-762b5a5e-b304-4da9-87b1-c34bfffb7635.png">
<img width="288" alt="Screenshot 2022-11-15 at 11 00 58" src="https://user-images.githubusercontent.com/113910347/201890709-40c6578d-5a3a-43e1-96a4-6b65354ad719.png">

## Acceptance Criteria

- [ ] Detailspages are shown
- [ ] Detailspages can be navigated
      ​

## Tasks

- [ ] Create Detailspages
- [ ] Fill Detailspages with data
- [ ] Remove JSON shown in landingpage
- [ ] Add Navigation to all pages
- [ ] Add a "Back" Button to all pages
      ​

## Complexity

medium
