### ISSUE TITLE
Add functionality to add new entries

### ISSUE THREAD

**Issue by kochch1337** [kochch1337/Capstone-Project#11]
## Value Proposition

**As a** User  
**I want to** add new solutions, modules, developers and bpas  
**so that** I can keep the data up to date
​

## Description
Add a add button to create new data in the nav page. Change Dev and BPE/BSE to one page called persons.
<img width="288" alt="Screenshot 2022-11-22 at 15 28 52" src="https://user-images.githubusercontent.com/113910347/203339966-1b0e7a66-7b3d-4c01-b522-ce3c665a0b76.png">
First you have to select via button what to add: solution, module or person

<img width="288" alt="Screenshot 2022-11-22 at 15 28 44" src="https://user-images.githubusercontent.com/113910347/203340159-aba7664d-8f24-45f3-95f7-7aebba7eb94c.png">
For Solution you have free text fields and for all persons you can choose via dropdown from persons array

<img width="288" alt="Screenshot 2022-11-22 at 15 28 36" src="https://user-images.githubusercontent.com/113910347/203340357-ea2817af-49bd-4448-a8fd-6ab8f7be2616.png">
For Module you add module name and then can add multiple persons as dev or as BP via dropdown

<img width="288" alt="Screenshot 2022-11-22 at 15 28 25" src="https://user-images.githubusercontent.com/113910347/203340592-596124c8-b796-4c8f-b1e5-3ea6c579bfab.png">
For persons you can set firstname, lastname as free text and choose a role from a dropdown

​

## Acceptance Criteria

- [ ] New NavButtons are shown
- [ ] Clicking on + opens a new page where you can chose 3 buttons for new solution, new module or new person
- [ ] each of the 3 buttons opens a new page where you can enter the new data
- [ ] free text fields are trimmed and checked for empty values. Fields must be filled
- [ ] drop down fields are checked if a valid value is choosen
- [ ] after clicking on save button the data is saved to local storage
- [ ] all sites show the new data
      ​

## Tasks

- [ ] Create new nav button +
- [ ] Create new page with 3 buttons for add solution, add module, add person
- [ ] Update Developer Page to Person page an show also bps persons
- [ ] Remove BPS page
- [ ] Create Add Solution page with all its fields.
- [ ] Create Save button and save functionality for Solution
- [ ] Create Cancel Button and functionality for Solution
- [ ] Create Add Module page with all its fields.
- [ ] Create Save button and save functionality for Modules
- [ ] Create Cancel Button and functionality for Modules
- [ ] Create Add Persons page with all its fields.
- [ ] Create Save button and save functionality for Persons
- [ ] Create Cancel Button and functionality for Persons
      ​

## Complexity

large

**Comment by JessicaLoers** [comment]
**Hi @kochch1337 🖖**
I highly recommend to cut this user story into three separate ones.
If I understand it correctly, you will need three independent forms, but in your user story the term form isn't mentioned once.

Apart from that, I would like to make the following comments. Sorry for being  mean , but I only mean well with you.🫣

---

**Value Proposition**
**so that I** can keep the data up to date --> _**this isn't a precise statement**_  

👉 **My sugesstion:** 
**so that I** can keep track of further/upcoming projects, related tasks and roles 

_even if I haven't quite understood what bpas is_ 😁

---
**Description**
~Add a add button to create new data in the nav page. Change Dev and BPE/BSE to one page called persons.~
These two sentences are a kind of confusing, because it's a mixture of AC and tasks. I would just delete the first line. 

**1. Wireframe** - A few mistakes have crept in here. 😈
👉 The headline isn't right, the third button should be `new Person` and it would be helpful to know which page is active. 

![wireframe1](https://user-images.githubusercontent.com/54777853/203405034-bae928ae-5626-4007-b8bc-48f553c7bdf2.png)

**2. Wireframe** - Another  typo have crept in here 😈
👉 It would be helpful to know which page is active. 

For Solution you have ~free~ **three** text fields and for all persons you can choose via dropdown from persons array _**--> Which people are we talking about - are they the team members? I am confused.**_

**3. Wireframe** 
👉 It would be helpful to know which page is active. 
_**The person I can add is a staff member?**_ 

---

**Acceptance Criteria**
- New NavButtons are shown _**--> which ones?  (Solutions, Module, Person, Add Icon )**_
- By clicking on the Add Icon leads to a page where you can choose between three buttons for new solution, new module or new person
-  each of the 3 buttons opens a new page where you can enter the new data **_--> please be precise. Which data could be entered? What is the name of the new page?_** 
 - free text fields are trimmed and checked for empty values. Fields must be filled  **_-->Which input types to I need? Regarding the form validation - which ones are required? _** 
- drop down fields are checked if a valid value is choose **_--> What can I select in the respective drop-down list in which form?_**
- all sites show the new data **_--> The respective entries are displayed on the corresponding pages_**
- What happens when I have sent the respective form? Do I get a message? Will I be redirected to a page?

Actually, you would list the respective AC and tasks for each form.  This also shows you:  this User Story is just too big. By the way, the PR for this user story will be a monster. 🤯

**If you have any questions, feel free to ask.**
