### ISSUE TITLE
Add functionality to add new modules

### ISSUE THREAD

**Issue by kochch1337** [kochch1337/Capstone-Project#12]
## Value Proposition

**As a** User  
**I want to** add new modules
**so that** I can keep track of further/upcoming projects, related tasks and roles
​

## Description
<img width="288" alt="Screenshot 2022-11-22 at 15 28 36" src="https://user-images.githubusercontent.com/113910347/203340357-ea2817af-49bd-4448-a8fd-6ab8f7be2616.png">
For Module you add module name and then can add multiple persons as dev or as BP via dropdown

## Acceptance Criteria

- [ ] Clicking on new Module on the "add new entries" page opens a new form to enter a new module
- [ ] Free text field module is trimmed and checked for empty values. Field must have at least 3 chars an a maximum of 8 chars. Field module must be checked for unique name
- [ ] If button "+" beneath drop down for developer or bpa is clicked it must be checked if a valid  person from the datasource is choosen.
- [ ] Developer and bpa must have at least one added person before saving the module is allowed
- [ ] After clicking on save button the data is saved to local storage (if everything is valid)
- [ ] Show message if save was successful
- [ ] The respective entries are displayed on the corresponding pages
- [ ] Redirection to the modules page to see the new data or if canceled the old
      ​

## Tasks

- [ ] Create Add Module page with all its fields.
- [ ] Create text field module and add validation (not empty, 3-8 chars, unique modul name)
- [ ] Create List of developers and add function for the list with a drop down
- [ ] Create List of bps and add function for the list with a drop down
- [ ] Create Save button and save functionality for Modules
- [ ] Create Cancel Button and functionality for Modules
- [ ] Create Redirect to solutions page
      ​

## Complexity

medium
