### ISSUE TITLE
Add functionality to add new persons

### ISSUE THREAD

**Issue by kochch1337** [kochch1337/Capstone-Project#13]
## Value Proposition

**As a** User  
**I want to** add new persons
**so that** I can keep track of further/upcoming projects, related tasks and roles
​

## Description
<img width="288" alt="Screenshot 2022-11-22 at 15 28 25" src="https://user-images.githubusercontent.com/113910347/203340592-596124c8-b796-4c8f-b1e5-3ea6c579bfab.png">
For persons you can set firstname, lastname as free text and choose a role from a dropdown. All persons entered are staff members

## Acceptance Criteria

- [x] Clicking on new Person on the "add new entries" page opens a new form to enter a new person
- [x] Free text fieldsfirstname and lastname are trimmed and checked for empty values. Field must have at least 2 chars an a maximum of 80 chars.
- [x] Drop down fields role is checked for valid value
- [x] After clicking on save button the data is saved to local storage (if everything is valid)
- [x] Show message if save was successful
- [x] The respective entries are displayed on the corresponding pages
- [x] Redirection to the modules page to see the new data or if canceled the old
      ​

## Tasks

- [x] Create Add Persons page with all its fields.
- [x] Create 2 text fields firstname, lastname and add validation (not empty, 3-80 chars)
- [x] Create drop down with values (dev and bc)
- [x] Create Save button and save functionality for Persons, check validation
- [x] Create Cancel Button and functionality for Persons
      ​

## Complexity

medium

**Comment by WilhelmAlfke** [comment]
hi @kochch1337, cross out the tasks and criterias since you have done them..
