### ISSUE TITLE
Add update functionality

### ISSUE THREAD

**Issue by kochch1337** [kochch1337/Capstone-Project#18]
## Value Proposition

**As a** user 
**I want to** update the solutions, modules and persons 
**so that** I can change the values instead of deleting them first and then adding them with the changes
​

## Description
on all pages Solutions/Modules/Persons an button "edit" should be implemented. After clicking this button the existing page for creating the new entry should open and is filled out with the existing data. Now the data can be changed and saved afterwards.
​

## Acceptance Criteria

- [ ] Existing page is opend
- [ ] Existing data is filled within the form
- [ ] Data can be saved (rerun existing validations)
      ​

## Tasks

- [ ] Add edit button to the existing pages
- [ ] Read existing data and fill out forms
- [ ] Save the updated values
      ​

## Complexity

small
