### ISSUE TITLE
Add cpmonent tests for rendering and fetch

### ISSUE THREAD

**Issue by kochch1337** [kochch1337/Capstone-Project#2]
## Value Proposition

**As a**
devloper
**I want to**
secure that the app can be rendered and data can be fetched
**so that**
the the app can't be released if is not working
​

## Description
Add component tests for App start (rendering) and the fetch of the data
​

## Acceptance Criteria

- [ ] App can be rendered
- [ ] Data can be fetched
      ​

## Tasks

- [ ] Test for App rendering
- [ ] Test for data fetch      ​

## Complexity
medium
