### ISSUE TITLE
delete entries

### ISSUE THREAD

**Issue by kochch1337** [kochch1337/Capstone-Project#20]
## Value Proposition

**As a** user
**I want to** I want to delete entries
**so that** I only needed data is shown
​

## Description
on each entry type (solution, module, person) a button to delete the entry should be shown.
​

## Acceptance Criteria

- [ ] For each data entry a delete button is created
- [ ] Before deleting system checks if entry can be deleted an has no more related data
- [ ] If no related data is found the entry is deleted
- [ ] if related data is found a hint is shown to clear the relation first
      ​

## Tasks

- [ ] Create delete button for solution
- [ ] Create delete button for module
- [ ] Create delete button for persons
- [ ] Create check function for relation
- [ ] Create hint for deletion not allowed
- [ ] Create function to delete entry
      ​

## Complexity

...
