### ISSUE TITLE
Add dropdown to detailpages containing details

### ISSUE THREAD

**Issue by kochch1337** [kochch1337/Capstone-Project#3]
## Value Proposition

**As a**
user
**I want to**
see the other levels data in a dropdown
**so that**
I can get a quick overview before navigating to the page
​

## Description
Dropdown functionality is added to show details
​

## Acceptance Criteria

- [ ] Dropdown is working
- [ ] Data in Dropdown is shown
      ​

## Tasks

- [ ] Add dropdown to detailspage
- [ ] Show data in fropdown
      ​

## Complexity

...
