### ISSUE TITLE
Move dummy data to local storage

### ISSUE THREAD

**Issue by kochch1337** [kochch1337/Capstone-Project#4]
## Value Proposition

**As a**
devloper
**I want to**
move the dummy data to the local storage
**so that**
I can edit the data (insert/update/delete)
​

## Description
Move dummy data to local storage to prepare insert/update/delete functionality
​

## Acceptance Criteria

- [ ] Data is moved to local storage
- [ ] Data can be retrieved from local storage
      ​

## Tasks

- [ ] Move data to local storage
- [ ] Read data from local storage instead from dummy data file
      ​

## Complexity

small
