### ISSUE TITLE
Start Project with landing page

### ISSUE THREAD

**Issue by kochch1337** [kochch1337/Capstone-Project#5]
## Value Proposition
​
**As a User**
everyone
**I want to**
To see the the relations of the devolpers and the modules
**so that I**
can quickly find out who is responisble
​
## Description
When the app starts the data is shown
<img width="386" alt="Screenshot 2022-11-15 at 10 35 39" src="https://user-images.githubusercontent.com/113910347/201884338-08b879a4-8b58-493c-afad-9dac76cf8abb.png">

​
## Acceptance Criteria

- [ ] App starts
- [ ] Data is fetched (dummy Data)
- [ ] Data is shown as json on the page
- [ ] Data is shown as a list from the first level items
​
## Tasks
​
- [ ] Create feature branch
- [ ] Create folders and files
- [ ] Create dummy data
- [ ] Fetch dummy data
- [ ] Create container item for the data
- [ ] Show fetched data on start page
