### ISSUE TITLE
Create Navigation an pages for navigation #3

### ISSUE THREAD

**Issue by kochch1337** [kochch1337/Capstone-Project#6]
## Value Proposition

**As a** User 
**I want to** navigate between the pages (areas) 
**so that** I can see the the different areas and its contents e.g. Solution, Modules, Developers
​

## Description
Pages for each area -> active page not shown in wireframe but must be implemented
<img width="288" alt="Screenshot 2022-11-16 at 10 29 05" src="https://user-images.githubusercontent.com/113910347/202142969-6e3a179c-4fe4-4fe1-8f74-16c32c6ceeef.png">
<img width="288" alt="Screenshot 2022-11-16 at 10 28 59" src="https://user-images.githubusercontent.com/113910347/202142996-e041da21-54d3-4438-9d76-d9512e50d47a.png">
<img width="288" alt="Screenshot 2022-11-16 at 10 28 52" src="https://user-images.githubusercontent.com/113910347/202143103-3b81bd9c-415f-425b-92fe-47bb72da41a4.png">
<img width="288" alt="Screenshot 2022-11-16 at 10 28 45" src="https://user-images.githubusercontent.com/113910347/202143155-9a3e19e2-2350-4575-90c7-2d396679fc57.png">

​

## Acceptance Criteria

- [ ] Pages can be navigated
- [ ] Page that is visible is highlighted in the navbar
- [ ] Page shows the filtered content e.g. Solutions

      ​

## Tasks

- [ ] Create navbar
- [ ] Create pages
- [ ] Add click functionality to navbars
- [ ] Add content to pages
      ​

## Complexity
medium

**Comment by Kheirah** [comment]
It is a natural first instinct to be to able to navigate around on a site. However, navigation by itself is of little value to the user. If the pages are empty, the user navigates to empty spaces which are, by their very nature, empty. Blank pages don't hurt anybody, but they also don't add any value to the app.

First, start building out a particular page. Add functionality to that page. When done, add another page with functionality. When there are several pages you can then implement the ability to change the route between these pages. The value is immediately tangible since you can switch between content instead of blanks.

**Comment by kochch1337** [comment]
Hi,
the pages won't be empty, the pages will be filled with data. The data is not filtered in the first part but the user will see content already like written in the value proposition. This was also decided with the coaches. The next step will then be a linked navigation filtering the data only related to the chosen area but the first step should be to navigate and display all unfiltered area content

**Comment by Kheirah** [comment]
All right then, decided it is!
